name: Deploy SQL Files to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy files to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
          EC2_USER: ec2-user # Or your specific user
        run: |
          # 1. Prepare the SSH key
          echo "${{ env.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

          # 2. Use SSH to create the destination directory on the EC2 instance
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ env.EC2_USER }}@${{ env.EC2_PUBLIC_IP }} "mkdir -p /home/${{ env.EC2_USER }}/src"

          # 3. Use SCP to copy the repository files from the runner to the EC2 instance
          scp -o StrictHostKeyChecking=no -i ec2_key.pem -r ./* ${{ env.EC2_USER }}@${{ env.EC2_PUBLIC_IP }}:/home/${{ env.EC2_USER }}/src/